name: Deploy to Production
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Deploy to Production Server
        run: |
          curl -X POST https://nyx.arohalabs.tech/deploy \
          -H "Content-Type: application/json" \
          -d '{
                "repo": "git@github.com:Aroha-Labs/mira-sdk-python.git",
                "name": "mira-sdk-python",
                "path": "/",
                "port": 3000,
                "environment": "stg"
              }'