name: Auto-bump Version and Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  bump-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine bump2version

      # Step 4: Auto-bump the version
      - name: Auto-bump version
        env:
          BUMP_TYPE: "patch" # Change to 'major' or 'minor' if required
        run: |
          bump2version --current-version $(python setup.py --version) $BUMP_TYPE

      # Step 5: Commit and push the updated version
      - name: Commit and push version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Build the package
      - name: Build the package
        run: python -m build

      # Step 7: Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*

